### ISSUE TITLE
Accessibility checks?

### ISSUE THREAD

**Issue by mockdeep** [sds/haml-lint#112]
There is the alt text check, but I was thinking it would be great to have an automated linter to let us know about accessibility issues, and haml lint seemed like a good place for that. I'm very familiar at all with accessibility best practices, but aria roles is something I keep hearing about which might be nice to lint for.

**Comment by sds** [comment]
I'm open to a pull request for this, but I get the sense that this would be a rather extensive set of checks prone to false positives. There's a lot semantic understanding necessary to know when certain accessibility attributes make sense.

Would love to see someone make a proposal if there are baby steps we can take with this idea.
