### ISSUE TITLE
Autocorrect feature

### ISSUE THREAD

**Issue by Ana06** [sds/haml-lint#217]
Supporting autocorrect as Rubocop does would be great. :slightly_smiling_face:

**Comment by michaelherold** [comment]
You're right, this would be a great feature. I consciously steered around that problem and haven't looked into it yet because, frankly, it scares me. 😅

**Comment by stephen-puiszis** [comment]
@michaelherold what are the scary issues and how do we start addressing them?

**Comment by sds** [comment]
RuboCop benefits from the hard work of the `parser` gem, which allows you to modify the syntax tree and re-serialize back to code without much effort.

There is no such parser for HAML. Thus HAML-Lint would effectively need to duplicate the HAML project to support its own parser that allows for mutating the syntax tree.

That is a huge amount of work. I would love to see someone step up to tackle it, but I'm skeptical the benefit is worth the development effort.

**Comment by stephen-puiszis** [comment]
@sds thanks for the info, I assumed it would take quite a bit of work. I did some googling and found the [haml_parser gem](https://github.com/eagletmt/haml_parser). My intuition is that it needs a lot of work, but might provide a starting point. 

As someone working on a rescue project at the moment, I would love an auto-correct tool to help automate some of the cleanup process as the code is quite awful. I'm sure others would benefit from this as well... but you're right, it all eventually comes down to time and effort

**Comment by Ana06** [comment]
@stephen-puiszis is the haml_parser gem really related. In the readme it says:

> Welcome to your new gem! In this directory, you'll find the files you need to be able to package up your Ruby library into a gem

**Comment by Ana06** [comment]
@sds 

> Thus HAML-Lint would effectively need to duplicate the HAML project to support its own parser that allows for mutating the syntax tree.


Could the parser be useful for something else apart from the autocorrect option? Because then this would have more sense.

and anyway this parser should be an independent gem, not inside haml.lint, right?

**Comment by sds** [comment]
Ideally this would be a contribution to the `haml` gem itself so that it benefits the most people. However, it's likely that there will be performance tradeoffs in having a parser that collects enough information to support syntax tree editing and code generation, so it would likely be a separate gem.

In either scenario: yes, this should not solely exist in the `haml_lint` gem.

**Comment by sam0x17** [comment]
@michaelherold maybe a good initial step would be to add a --fix / --auto-correct option that only fixes rubocop portions of each haml file e.g. the ruby parts. I imagine that would be a lot easier?

**Comment by Intrepidd** [comment]
Hello ! Any news on this ? as @sam0x17 mentioned fixing the ruby parts would already be huge !

**Comment by vpereira** [comment]
or at least the line breaking for the `LineLength` cop?

**Comment by sds** [comment]
#346 is the only progress being made on this. Would welcome anyone to continue working from that if they'd like to see this built! (and big thank you to the author who got it started)

Going to close this due to age.
