### ISSUE TITLE
Linter Idea: Referencing constants in a view

### ISSUE THREAD

**Issue by andyw8** [sds/haml-lint#238]
I've been thinking about a new linter but wanted to get some feedback on the idea first.

Whenever I see a class or module (or constant) referenced in a view, it almost always seems like a design flaw.

It violates Separation of Concerns and tightly couples the view layer to the model layer, rather than using the controller layer as an intermediate.

I'm trying to find if there are valid exceptions to this, where referencing a constant in the view might be the right thing to do.

**Comment by michaelherold** [comment]
I often use the pattern of refactoring complex view logic into an object that I instantiate in the view. This is an intermediate step to making a full view model later.

It's still a smell though, so I think this would be a good one to have.

**Comment by andyw8** [comment]
I noticed the Rails Style Guide contains a rule which also relates to this:

> Never call the model layer directly from a view.

https://github.com/rubocop-hq/rails-style-guide#no-direct-model-view

**Comment by andyw8** [comment]
> sds closed this as completed

Was that accidental? I can't see anything in changelog about this.

**Comment by sds** [comment]
Sorry, should have closed as "not planned". Have updated.
