### ISSUE TITLE
linter to avoid the use of :ruby

### ISSUE THREAD

**Issue by Ana06** [sds/haml-lint#288]
I don't like `:ruby` and I would like to avoid its use. (It seems that even haml-lint doesn't consider it exists: https://github.com/brigade/haml-lint/issues/287). A linter for that would be great! :cupid:

**Comment by sds** [comment]
Happy to accept a pull request! However, it should not be enabled by default. There are enough legitimate uses of `:ruby` filters that it seems sensible as an opt-in setting.
