### ISSUE TITLE
Lint for usage of plain text instead of using i18n

### ISSUE THREAD

**Issue by phansch** [sds/haml-lint#293]
Having a lint that detects usage of plain text in .haml files would help enforce usage of i18n across all views.

For example, I imagine these would be linted:

```haml
Hello World
```

```haml
.div Hello World
.div
  Hello World
```

and these not:

```haml
= t('hello')
```

```haml
.div= t('hello')
.div
  = t('hello')
```

If that's a thing that's welcome and in the realm of possibility, I'd be happy to contribute this lint.

**Comment by sds** [comment]
Open to a well-tested pull request with the linter disabled by default!

**Comment by LukeeeeBennett** [comment]
@phansch There are a few ways to do this and even more ways to improve it depending on your codebase, there is a WIP linter for GitLab at https://gitlab.com/gitlab-org/gitlab-ee/merge_requests/11457 if you wanted to check it out. 

It _can_ be as simple as reporting every `visit_plain` visit.

**Comment by jtcontreras90** [comment]
@phansch I made a simple linter that lints most cases like:
```haml
.div Hello World
.div
  Hello World
.div= "Hello World"
.div
  = "Hello World"
.div= "Hello #{user},"
.div
  = "Hello #{user},"
.div= "Hello t('user'),"
.div
  = "Hello t('user'),"
.div Hello t('user'),
.div
  Hello t('user'),
-# etc...
```

And ignores the cases that you mention like:
```haml
.div= t('hello')
.div
  = t('hello')
.div= hello
.div= t('hello')
.div
  t('hello')
&nbsp;
-# etc...
```
The class is available in a [gist](https://gist.github.com/jtcontreras90/8c21f6e6cb68c4ba1d4cbe3b46640407) I made. The biggest problem are things that are not distinguishable from class names. For example:
```haml
.div{ class: 'some classes ' }
.div{ data: { confirm: 'Are you sure?' } }
```
Neither is linted, but the second should. Nevertheless, it's very useful :+1:
