### ISSUE TITLE
Register linter but do not enable implictly

### ISSUE THREAD

**Issue by LukeeeeBennett** [sds/haml-lint#299]
```
linters:
    SomeLinter:
        enabled: false
```

This disables the linter for any use, `haml-lint app/` alone will ignore it and `haml-lint -i SomeLinter app/` will also ignore it.

I would love a way to register a linter so it can be referenced with `-i`, but not included automagically for `haml-lint app/`.

Is there a way to do this already?

**Comment by sds** [comment]
What do tools like RuboCop do in this situation? We should emulate that behavior.

Happy to merge a pull request with an appropriate fix!
