### ISSUE TITLE
Avoid reloading .rubocop.yml repeatedly

### ISSUE THREAD

**Issue by stanhu** [sds/haml-lint#301]
I noticed that haml-lint runs `Rubocop::CLI#run` for each file, which causes Rubocop to reload all `.rubocop.yml` files repeatedly and slows down the linting process. Is there a way to reduce I/O by loading the Rubocop config file once, and then process the list of files?

**Comment by sds** [comment]
Would welcome a pull request that works around this. Given this is RuboCop behavior, not sure there's an easy workaround that wouldn't tightly couple ourselves to RuboCop internals. Perhaps that's alright, but I would welcome someone else to investigate.

**Comment by stanhu** [comment]
Yeah, I figured as much I've opened https://github.com/rubocop-hq/rubocop/issues/7024 to discuss. 

Another alternative would be for `haml-lint` to batch by directory, since `Rubocop::CLi#run` can handle multiple paths. What about that?
