### ISSUE TITLE
Layout/TrailingEmptyLines rubocop rule false positives

### ISSUE THREAD

**Issue by mockdeep** [sds/haml-lint#315]
It seems like maybe this rule should be disabled for `haml-lint`, but the Rubocop rule `Layout/TrailingEmptyLines` is reporting every one of my view files as of rubocop version 0.77.0.

**Comment by mockdeep** [comment]
Looks like they renamed the rule from `Layout/TrailingBlankLines` to `Layout/TrailingEmptyLines`. Might be worth having both in `ignored_cops` for a little while.

**Comment by sds** [comment]
Fixed in #314.
