### ISSUE TITLE
HAML-Lint exits successfully even if RuboCop fails

### ISSUE THREAD

**Issue by ybiquitous** [sds/haml-lint#317]
Hi, I find a strange behavior of the latest version of HAML-Lint.

Even if RuboCop fails, HAML-Lint exits with the status `0`.

For example, assume that you have `Gemfile` and `.rubocop.yml` files:

```ruby
# Gemfile
source "https://rubygems.org"

gem "haml_lint"
```

```yaml
# .rubocop.yml
require:
  - rubocop-performance
```

When running `bundle exec haml-lint`, the error log is output but `haml-lint` exits successfully:

```
$ bundle exec haml-lint
cannot load such file -- rubocop-performance

(...stack trace...)

1 file inspected, 0 lints detected

$ echo $?
0
```

I created a repository for reproduction. Please see:
https://github.com/ybiquitous/haml-lint-reproduction

I expect it user-friendly that HAML-Lint also fails when RuboCop fails, but what do you think?

**Comment by sds** [comment]
Hey @ybiquitous, thanks for the report.

The fix is to handle this case in the RuboCop linter:

```diff
diff --git a/lib/haml_lint/linter/rubocop.rb b/lib/haml_lint/linter/rubocop.rb
index c6f75c5c..bc494bfc 100644
--- a/lib/haml_lint/linter/rubocop.rb
+++ b/lib/haml_lint/linter/rubocop.rb
@@ -56,7 +56,13 @@ module HamlLint
     # @param file [String]
     # @return [Array<RuboCop::Cop::Offense>]
     def lint_file(rubocop, file)
-      rubocop.run(rubocop_flags << file)
+      status = rubocop.run(rubocop_flags << file)
+      if status != 0
+        raise HamlLint::Exceptions::ConfigurationError,
+              "RuboCop exited unsuccessfully with status #{status}." \
+              ' Check the stack trace to see if there was a misconfiguration.'
+      end
+
       OffenseCollector.offenses
     end
```

Unfortunately, due to some assumptions in HAML-Lint, this breaks a number of tests which requires some investigation to fix correctly. 

If you'd like to see this fixed sooner rather than later, a pull request with working tests would be welcome. Thanks!

**Comment by ybiquitous** [comment]
@sds Thanks for your suggestion. I'm not sure if I can fix all, but I will try!

**Comment by ybiquitous** [comment]
@sds I opened a new PR #318 but I keep it draft because of CI failures.
Please let me know if I can do anything.
