### ISSUE TITLE
Allow usage of `inherit_gem` configuration

### ISSUE THREAD

**Issue by sandro-aboutsource** [sds/haml-lint#323]
As ruby developers we want to share the same haml-lint configuration through all of our repos.

Rubocop [has a configuration called `inherit_gem`](https://docs.rubocop.org/en/stable/configuration/#inheriting-configuration-from-a-remote-url) that allows to inherit configuration from a gem.

Is it somehow possible to use the same rule in haml-lint?
The configuration currently just ignores this key.

```
haml-lint 0.35.0
haml 5.1.2
rubocop 0.83.0
ruby 2.5.8p224 (2020-03-31 revision 67882) [x86_64-linux]
```

**Comment by sds** [comment]
Would welcome a well-tested pull request!
