### ISSUE TITLE
haml-lint ignores `.haml-lint_todo.yml`?

### ISSUE THREAD

**Issue by vpereira** [sds/haml-lint#332]
running gem 0.3.7

generate the todo with `haml-lint --auto-gen-config`

Added the new file to `.haml-lint.yml`

The ignored errors are still there.

PR where it happens: https://github.com/openSUSE/open-build-service/pull/11227/commits/7687b4e2f05a9aa76d6005be3d55e92f225c38f3

**Comment by vpereira** [comment]
From the README:

"Lastly, in order to match your RuboCop configuration style, you can also use the inherit_from directive, which is an alias for inherits_from."

However for me, `inherits_from` doesnt work
`inherit_from` works"

is that intended?

**Comment by jaredmoody** [comment]
I'm having this same issue - but it seems to be only RuboCop rules

**Comment by jaredmoody** [comment]
In case it helps somebody else, I figured out my issue: 

In my `.haml-lint`, I had configured some `ignored_cops` under `RuboCop`. It appears that if you have a `RuboCop` block in your `.haml-lint` you can't also configure any options for `RuboCop` such as excluding a file in your `.haml-lint_todo.yml` - it appears the two configurations are not merged and any values in `.haml-lint_todo.yml` get ignored.

**Comment by dswij** [comment]
> In case it helps somebody else, I figured out my issue:
> 
> In my `.haml-lint`, I had configured some `ignored_cops` under `RuboCop`. It appears that if you have a `RuboCop` block in your `.haml-lint` you can't also configure any options for `RuboCop` such as excluding a file in your `.haml-lint_todo.yml` - it appears the two configurations are not merged and any values in `.haml-lint_todo.yml` get ignored.

Had similar issue.

Seems like the [overwrite behavior for inheritance](https://github.com/sds/haml-lint#inheriting-from-other-configuration-files) completely overwrites the whole config for a linter even when there is no conflict (i.e. no `exclude` setting in `.haml-lint.yml` but still overwrites those from `.haml-lint_todo.yml`)

Removing the linter in `.haml-lint.yml` does make the exclude settings from `.haml-lint_todo.yml` to work

**Comment by vpereira** [comment]
> In case it helps somebody else, I figured out my issue:

it worked for me!
