### ISSUE TITLE
v0.37.1 should be latest?

### ISSUE THREAD

**Issue by ybiquitous** [sds/haml-lint#334]
Hello. I noticed that the current latest version is v0.37.1, but the actual latest version on GitHub is still v0.37.0.

### [v0.37.1](https://github.com/sds/haml-lint/releases/tag/v0.37.1)

<img width="446" alt="image" src="https://user-images.githubusercontent.com/473530/123910752-dcb3a200-d9b5-11eb-8765-bc14c38c5046.png">

### [v0.37.0](https://github.com/sds/haml-lint/releases/tag/v0.37.0)

<img width="646" alt="image" src="https://user-images.githubusercontent.com/473530/123910811-ed641800-d9b5-11eb-8ffd-ecee569a3807.png">

If you could make v0.37.1 the *latest*, it would be greatly appreciated.

**Comment by sds** [comment]
Thanks for catching. [Updated](https://github.com/sds/haml-lint/releases/tag/v0.37.1).

**Comment by ybiquitous** [comment]
@sds Thank you for the quick response! 🥰
