### ISSUE TITLE
Is it possible to pull in Rubocop config from another gem?

### ISSUE THREAD

**Issue by matt17r** [sds/haml-lint#342]
I love that haml-lint is opinionated but I'm already using [StandardRB](https://github.com/testdouble/standard) for the same reason and I don't love that their opinions differ 😝

I read in the [Linter README](https://github.com/sds/haml-lint/blob/master/lib/haml_lint/linter/README.md) that I can configure cops in `.rubocop.yml` so I could copy Standard's config there but then I'd have to keep it up to date.

Is there a straight forward and zero-maintenance way to configure haml-lint to pull in cop configuration (other than specifically ignored cops) from another location, ideally from [`standard/config/base.yml`](https://github.com/testdouble/standard/blob/main/config/base.yml)?

**Comment by sds** [comment]
Not currently, but happy to merge a pull request adding such support!

**Comment by matt17r** [comment]
In an ideal world, Standard would lint Ruby code in HAML files too but the maintainer has previously said [linting template files (ERB) is out of scope](https://github.com/testdouble/standard/issues/304).

erb-lint added the ability to inherit cops from gems in [PR 88](https://github.com/Shopify/erb-lint/pull/88).

I will have a go at implementing a similar approach if I can:
- specify a gem to inherit from and a path to its config file in `.haml-lint.yml`
- last defined rule “wins”
