### ISSUE TITLE
Ruby 3.1 + EnforcedShorthandSyntax option in Style::HashSyntax cop

### ISSUE THREAD

**Issue by tagliala** [sds/haml-lint#360]
Hi,

I'm running into the following issue:

```haml
%div{ current_user: current_user }
  = { current_user: current_user }
```

```
$ haml-lint test.html.haml 
test.html.haml:1 [W] RuboCop: Style/HashSyntax: Omit the hash value.
test.html.haml:2 [W] RuboCop: Style/HashSyntax: Omit the hash value.
```

Edit: this is a reduced test case that does not represent a real use case. The real use case is related to data attributes

By changing to the suggested `%div{ current_user: }`, the template does not break, but the attribute field is empty. By changing the second line, the template breaks

Since one can still use the `Style/HashSyntax` cop in `haml-lint` to ensure that 1.9 syntax is used, I think that this cop should not be disabled like other noisy cops, so I'm asking if there is a way to configure a specific RuboCop cop inside haml-lint to workaround this issue

Ref: https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/HashSyntax

**Comment by sds** [comment]
>I'm asking if there is a way to configure a specific RuboCop cop inside haml-lint to workaround this issue

There is a [`HAML_LINT_RUBOCOP_CONF` environment variable](https://github.com/sds/haml-lint/blob/1231b394bcc2b6c9c47a7a18074b43b258a0872e/lib/haml_lint/linter/rubocop.rb#L104) one can specify if they want to use a different configuration when running RuboCop on HAML files.

Hopefully that helps answer your primary question! Open to any pull request that makes this easier.
