### ISSUE TITLE
The `haml-lint' command exists in these Ruby versions: 2.6.4

### ISSUE THREAD

**Issue by Faq** [sds/haml-lint#380]
Hello, 

Not adding it in gemfile:
gem install haml_lint

Repo steps:
`haml-lint app/views`

returns:
```
rbenv: haml-lint: command not found

The `haml-lint' command exists in these Ruby versions:
  2.6.4
```

Used versions:
Rails 7.0.4
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin22]
```
gem list haml_lint
haml_lint (0.42.0)
rbenv 1.2.0
capistrano-rbenv (2.2.0)
```

**Comment by sds** [comment]
Based on the information provided, this has something to do with your local environment, and isn't specific to HAML-Lint itself.
