### ISSUE TITLE
How to integrate with rubocop?

### ISSUE THREAD

**Issue by stevedowney** [sds/haml-lint#41]
I have rubocop running and can run haml-lint from the command line.

Is it possible to have haml-lint run when rubycop runs?  I haven't been able to figure out how to do this.

**Comment by bensheldon** [comment]
@stevedowney I'm running haml-lint via [guard-shell](https://github.com/hawx/guard-shell). It's not as elegant as a real guard plugin for haml-lint, but it does the job.

```ruby
guard :shell do
  watch(/.*\.haml/) { |m| `haml-lint --color #{m[0]}` }
end
```
