### ISSUE TITLE
Version 0.53.0 has not been pushed to Rubygems

### ISSUE THREAD

**Issue by renchap** [sds/haml-lint#473]
It does not appear in the version list: https://rubygems.org/gems/haml_lint/versions

But appears on Github: https://github.com/sds/haml-lint/releases/tag/v0.53.0

If you want to improve the release process further (and automate it, while increasing security), I suggest you look at this new Rubygems feature: https://blog.rubygems.org/2023/12/14/trusted-publishing.html

It allows you to authorize Github Actions from a repo to publish a gem, so it is done automatically and securely when creating a new release.

**Comment by sds** [comment]
Thanks for noticing. Not sure what happened, but it is now released on Rubygems.
